import type { ModuleDefinition } from "@/types/modules";

export const MODULES: ModuleDefinition[] = [
  {
    id: "command-center",
    name: "Dashboard",
    description: "AI operations command center with live KPIs",
    route: "/command-center",
    icon: "Gauge",
    status: "connected",
    category: "operations",
  },
  {
    id: "ai-copilot",
    name: "AI Copilot",
    description: "AI-powered assistant for stadium operations",
    route: "#",
    icon: "Sparkles",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "crowd-intelligence",
    name: "Crowd Intelligence",
    description: "Real-time density, flow prediction, pinch-point detection",
    route: "/crowd-intelligence",
    icon: "Users",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "scheduling",
    name: "Tournament Operations",
    description: "Multi-venue optimization, conflict detection",
    route: "/scheduling",
    icon: "Calendar",
    status: "connected",
    category: "operations",
  },
  {
    id: "enterprise-security",
    name: "Security Center",
    description: "Enterprise RBAC, audit, compliance, and security monitoring",
    route: "/enterprise-security",
    icon: "Shield",
    status: "connected",
    category: "safety",
  },
  {
    id: "emergency-response",
    name: "Emergency Center",
    description: "Incident detection, evacuation routing, dispatch",
    route: "/emergency-response",
    icon: "Siren",
    status: "connected",
    category: "safety",
  },
  {
    id: "parking",
    name: "Smart Parking",
    description: "Occupancy prediction, dynamic pricing, valet routing",
    route: "/parking",
    icon: "Car",
    status: "connected",
    category: "operations",
  },
  {
    id: "queue-prediction",
    name: "Queue Analytics",
    description: "Wait-time forecasting, staff trigger alerts",
    route: "/queue-prediction",
    icon: "Clock",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "digital-twin",
    name: "Digital Twin",
    description: "3D/2D stadium model with IoT overlay",
    route: "/digital-twin",
    icon: "Globe",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "fan-assistant",
    name: "Fan Experience",
    description: "Multilingual RAG chatbot, personalized itineraries",
    route: "/fan-assistant",
    icon: "Bot",
    status: "connected",
    category: "experience",
  },
  {
    id: "maintenance",
    name: "Predictive Maintenance",
    description: "IoT anomaly detection, RUL forecasting",
    route: "/maintenance",
    icon: "Wrench",
    status: "connected",
    category: "operations",
  },
  {
    id: "executive-analytics",
    name: "Executive Analytics",
    description: "AI-powered executive command center with KPI dashboards, decisions, and board reports",
    route: "/executive-analytics",
    icon: "LayoutDashboard",
    status: "connected",
    category: "analytics",
  },
  {
    id: "energy",
    name: "Energy & Sustainability",
    description: "Consumption monitoring, carbon tracking",
    route: "/energy",
    icon: "Zap",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "staff-allocation",
    name: "Staff Operations",
    description: "Shift optimization, skills-based matching",
    route: "/staff-allocation",
    icon: "UsersRound",
    status: "connected",
    category: "operations",
  },
  {
    id: "incidents",
    name: "Incident Analytics",
    description: "Root cause analysis, pattern detection",
    route: "/incidents",
    icon: "Search",
    status: "connected",
    category: "analytics",
  },
  {
    id: "reports",
    name: "Reports",
    description: "Exportable reports and analytics",
    route: "#",
    icon: "FileText",
    status: "connected",
    category: "analytics",
  },
  {
    id: "sustainability",
    name: "Sustainability",
    description: "AI energy, water, waste & carbon intelligence platform",
    route: "/sustainability",
    icon: "Leaf",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "settings",
    name: "Settings",
    description: "System configuration and preferences",
    route: "#",
    icon: "Settings",
    status: "connected",
    category: "operations",
  },
];

export const MODULE_CATEGORIES = [
  { id: "operations", label: "Operations", icon: "Settings" },
  { id: "intelligence", label: "Intelligence", icon: "Brain" },
  { id: "safety", label: "Safety & Security", icon: "Shield" },
  { id: "experience", label: "Fan Experience", icon: "Heart" },
  { id: "analytics", label: "Analytics", icon: "BarChart3" },
] as const;

export const SIDEBAR_ITEMS = [
  { id: "dashboard", label: "Dashboard", icon: "Gauge", route: "/command-center" },
  { id: "ai-copilot", label: "AI Copilot", icon: "Sparkles", route: "#" },
  { id: "executive", label: "Executive Analytics", icon: "LayoutDashboard", route: "/executive-analytics" },
  { type: "divider" as const },
  { id: "security", label: "Security Center", icon: "Shield", route: "/enterprise-security" },
  { id: "crowd", label: "Crowd Intelligence", icon: "Users", route: "/crowd-intelligence" },
  { id: "tournament", label: "Tournament Operations", icon: "Calendar", route: "/scheduling" },
  { id: "emergency", label: "Emergency Center", icon: "Siren", route: "/emergency-response" },
  { id: "parking", label: "Parking", icon: "Car", route: "/parking" },
  { id: "queue", label: "Queue Analytics", icon: "Clock", route: "/queue-prediction" },
  { id: "digital-twin", label: "Digital Twin", icon: "Globe", route: "/digital-twin" },
  { id: "maintenance", label: "Predictive Maintenance", icon: "Wrench", route: "/maintenance" },
  { type: "divider" as const },
  { id: "qa-dashboard", label: "QA Dashboard", icon: "CheckCircle", route: "/qa-dashboard" },
  { id: "a11y-center", label: "Accessibility", icon: "Accessibility", route: "/a11y-center" },
  { id: "reports", label: "Reports", icon: "FileText", route: "#" },
  { id: "performance", label: "Performance", icon: "Gauge", route: "/performance" },
  { id: "settings", label: "Settings", icon: "Settings", route: "#" },
] as const;
