import type { ModuleDefinition } from "@/types/modules";

export const MODULES: ModuleDefinition[] = [
  {
    id: "command-center",
    name: "Stadium Command Center",
    description: "AI-powered stadium operations dashboard with live KPIs, match-day alerts, and system health monitoring",
    route: "/command-center",
    icon: "Gauge",
    status: "connected",
    category: "operations",
  },
  {
    id: "ai-copilot",
    name: "AI Stadium Copilot",
    description: "Conversational AI assistant for real-time stadium operations insights and tactical decisions",
    route: "#",
    icon: "Sparkles",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "crowd-intelligence",
    name: "Crowd Intelligence",
    description: "Real-time fan density mapping, concourse flow prediction, and pinch-point detection across stadium gates",
    route: "/crowd-intelligence",
    icon: "Users",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "scheduling",
    name: "Tournament & Match Operations",
    description: "Multi-venue tournament scheduling, match coordination, fixture conflict detection, and resource optimization",
    route: "/scheduling",
    icon: "Calendar",
    status: "connected",
    category: "operations",
  },
  {
    id: "enterprise-security",
    name: "Stadium Security Operations",
    description: "Stadium-wide RBAC, access control, audit logging, compliance monitoring, and threat detection",
    route: "/enterprise-security",
    icon: "Shield",
    status: "connected",
    category: "safety",
  },
  {
    id: "emergency-response",
    name: "Stadium Emergency Response",
    description: "Automated incident detection, stadium evacuation routing, and first-responder dispatch coordination",
    route: "/emergency-response",
    icon: "Siren",
    status: "connected",
    category: "safety",
  },
  {
    id: "parking",
    name: "Smart Parking & Traffic",
    description: "Stadium parking occupancy prediction, dynamic pricing, traffic flow optimization, and valet routing",
    route: "/parking",
    icon: "Car",
    status: "connected",
    category: "operations",
  },
  {
    id: "queue-prediction",
    name: "Queue & Concourse Intelligence",
    description: "Stadium concourse wait-time forecasting, concession queue monitoring, and staff trigger alerts",
    route: "/queue-prediction",
    icon: "Clock",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "digital-twin",
    name: "Stadium Digital Twin",
    description: "3D/2D interactive stadium model with live IoT sensor overlay and what-if simulation capabilities",
    route: "/digital-twin",
    icon: "Globe",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "fan-assistant",
    name: "Fan Experience & Engagement",
    description: "Multilingual AI chatbot for fan support, personalized match-day itineraries, and in-stadium engagement",
    route: "/fan-assistant",
    icon: "Bot",
    status: "connected",
    category: "experience",
  },
  {
    id: "maintenance",
    name: "Stadium Predictive Maintenance",
    description: "IoT anomaly detection and remaining-useful-life forecasting for critical stadium infrastructure",
    route: "/maintenance",
    icon: "Wrench",
    status: "connected",
    category: "operations",
  },
  {
    id: "executive-analytics",
    name: "Executive Decision Support",
    description: "Stadium KPI dashboards, AI-generated board reports, and strategic decision intelligence for executives",
    route: "/executive-analytics",
    icon: "LayoutDashboard",
    status: "connected",
    category: "analytics",
  },
  {
    id: "energy",
    name: "Stadium Energy & Sustainability",
    description: "Stadium energy consumption monitoring, carbon footprint tracking, and AI-driven sustainability optimization",
    route: "/energy",
    icon: "Zap",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "staff-allocation",
    name: "Stadium Staff Allocation",
    description: "Match-day shift optimization, skills-based staff routing, and workforce management",
    route: "/staff-allocation",
    icon: "UsersRound",
    status: "connected",
    category: "operations",
  },
  {
    id: "incidents",
    name: "Incident Intelligence",
    description: "Stadium incident root cause analysis, pattern detection, and predictive alerting",
    route: "/incidents",
    icon: "Search",
    status: "connected",
    category: "analytics",
  },
  {
    id: "reports",
    name: "Stadium Reports & Analytics",
    description: "Exportable stadium operations reports, match-day analytics, and performance insights",
    route: "#",
    icon: "FileText",
    status: "connected",
    category: "analytics",
  },
  {
    id: "sustainability",
    name: "Stadium Sustainability Intelligence",
    description: "AI-powered stadium water, waste, energy, and carbon intelligence platform for green venue operations",
    route: "/sustainability",
    icon: "Leaf",
    status: "connected",
    category: "intelligence",
  },
  {
    id: "settings",
    name: "System Configuration",
    description: "Stadium system configuration, preferences, and AI model settings",
    route: "#",
    icon: "Settings",
    status: "connected",
    category: "operations",
  },
];

export const MODULE_CATEGORIES = [
  { id: "operations", label: "Stadium Operations", icon: "Settings" },
  { id: "intelligence", label: "Stadium Intelligence", icon: "Brain" },
  { id: "safety", label: "Stadium Safety & Security", icon: "Shield" },
  { id: "experience", label: "Fan Experience & Engagement", icon: "Heart" },
  { id: "analytics", label: "Stadium Analytics", icon: "BarChart3" },
] as const;

export const SIDEBAR_ITEMS = [
  { id: "dashboard", label: "Stadium Command Center", icon: "Gauge", route: "/command-center" },
  { id: "ai-copilot", label: "AI Stadium Copilot", icon: "Sparkles", route: "#" },
  { id: "executive", label: "Executive Decision Support", icon: "LayoutDashboard", route: "/executive-analytics" },
  { type: "divider" as const },
  { id: "security", label: "Security Operations", icon: "Shield", route: "/enterprise-security" },
  { id: "crowd", label: "Crowd Intelligence", icon: "Users", route: "/crowd-intelligence" },
  { id: "tournament", label: "Tournament Operations", icon: "Calendar", route: "/scheduling" },
  { id: "emergency", label: "Emergency Response", icon: "Siren", route: "/emergency-response" },
  { id: "parking", label: "Smart Parking & Traffic", icon: "Car", route: "/parking" },
  { id: "queue", label: "Queue Intelligence", icon: "Clock", route: "/queue-prediction" },
  { id: "digital-twin", label: "Stadium Digital Twin", icon: "Globe", route: "/digital-twin" },
  { id: "maintenance", label: "Predictive Maintenance", icon: "Wrench", route: "/maintenance" },
  { type: "divider" as const },
  { id: "qa-dashboard", label: "QA Dashboard", icon: "CheckCircle", route: "/qa-dashboard" },
  { id: "a11y-center", label: "Accessibility", icon: "Accessibility", route: "/a11y-center" },
  { id: "reports", label: "Reports & Analytics", icon: "FileText", route: "#" },
  { id: "performance", label: "System Performance", icon: "Gauge", route: "/performance" },
  { id: "settings", label: "Configuration", icon: "Settings", route: "#" },
] as const;
