apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stadiumos
spec:
  type: ClusterIP
  selector:
    app: stadiumos
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
