apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - configmap.yml
  - secrets.yml

commonLabels:
  app: stadiumos
  managed-by: kustomize

namespace: stadiumos
